server:
  port: 8083
spring:
  application:
    name: telegram-alert
telegram:
  bot-token: 8693106716:AAEIohD3ZhZxq921Q_tVCFyWoU7-5Z3e2RE
  chat-id: -1003795829574
api:
  url: https://gold.g.apised.com/v1/latest?metals=XAU&base_currency=USD&currencies=USD&weight_unit=toz
  key: sk_c3055095D848d3cE8D6B1309BDd85438DfF4c47B89aF5Ddf
cron:
  schedule: "0 */15 * * * *" #Every 15 Minutes
